### ISSUE TITLE
没有 AdGuard

### ISSUE THREAD

**Issue by vipwuping** [AUK9527/Are-u-ok#10]
没有 AdGuard Home 这个插件增加一下

**Comment by ucyo123** [comment]
同求

**Comment by HiJwm** [comment]
同求

**Comment by AUK9527** [comment]
> 没有 AdGuard Home 这个插件增加一下

你们要说平台啊  x86的吗？   直接去a53那个装 就成，一样的插件，adg这个 是all 全平台通用。

**Comment by ucyo123** [comment]
> 

a53在哪下载啊

**Comment by AUK9527** [comment]
> > 
> 
> a53在哪下载啊

本项目  稍微仔细点 就能看见
