### ISSUE TITLE
openClash上传失败

### ISSUE THREAD

**Issue by KamToHung** [AUK9527/Are-u-ok#13]
使用手动安装，上传失败
环境：使用了VMWare虚拟机
版本：[openwrt-21.02.1-2022042317-x86-64-generic-squashfs-combined.vmdk](https://fw.koolcenter.com/iStoreOS/x86_64/openwrt-21.02.1-2022042317-x86-64-generic-squashfs-combined.vmdk)
应用商店版本：v0.1.9-6
错误：正在上传插件 not found soft 离线安装失败,错误码 500
请问下是什么原因

**Comment by AUK9527** [comment]
> 使用手动安装，上传失败 环境：使用了VMWare虚拟机 版本：[openwrt-21.02.1-2022042317-x86-64-generic-squashfs-combined.vmdk](https://fw.koolcenter.com/iStoreOS/x86_64/openwrt-21.02.1-2022042317-x86-64-generic-squashfs-combined.vmdk) 应用商店版本：v0.1.9-6 错误：正在上传插件 not found soft 离线安装失败,错误码 500 请问下是什么原因

要图的，完整图，只是说错误，没人能给你解答。
