### ISSUE TITLE
为啥4.7系列的passwall没有v2ray的包了呢

### ISSUE THREAD

**Issue by yunshenwuji** [AUK9527/Are-u-ok#137]
我尝试更新最新版passwall之后，配置的v2ray节点就失效了，而且在选项里也找不到v2ray了，请问这种情况要如何解决呢

**Comment by PauLmaX668** [comment]
我的情况也是一样，组件更新里面没了V2ray的选项，而且V2ray的节点的UDP全部启动不了，其他协议的如trojan那些都行；然后在系统软件包里面移除了后，重新安装升级前的4.66-8就有了，期待更新解决，万分感谢！

**Comment by bcseputetto** [comment]
因为新版的passwall不再依赖v2ray了，请使用xray来代替v2ray，完全没有问题的
详见
https://github.com/xiaorouji/openwrt-passwall/commit/4c6bf56ccb997dc68ce1494f35a700653e07cb53
passwall原仓库的这个 commit ，去年2023年9月7号 4.70-1 开始就移除了v2ray了
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/1aba27d8-89a9-4c6b-b107-3e8efffb94d0)

**Comment by yunshenwuji** [comment]
感谢您的解答，我是新手用户，我的机场提供的是v2ray的订阅链接，如果切换到xray，应该用什么订阅链接呢

**Comment by bcseputetto** [comment]
@yunshenwuji 继续用v2ray订阅链接就行了
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/54277620-cc65-4997-9d6a-a36de4f13034)
你可以在节点订阅选择使用xray或者sing-box，它们都能跑v2ray的协议(vmess和vless)

**Comment by bcseputetto** [comment]
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/48bded8e-fcf2-475a-9c3e-de8ba402df41)
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/2bc05bae-8c1a-4254-afe5-0a565c8062ae)
如果你的机场用Vmess，且Alter ID不为0，建议用sing-box，可以用Alter ID非0的Vmess配置
而xray只能用Alter ID为0的Vmess配置

**Comment by bcseputetto** [comment]
如果你装的 4.71-2没有我上述截图的配置，可以到我仓库下载最新的 4.72-2

**Comment by yunshenwuji** [comment]
> 如果你装的 4.71-2没有我上述截图的配置，可以到我仓库下载最新的 4.72-2

我眼睛看不见，是用屏幕阅读器操作电子设备的，可以麻烦您文字说下图里的选项吗？

**Comment by bcseputetto** [comment]
@yunshenwuji 在passwall上方的节点订阅设置里面，可以设定v2ray使用的两种协议，比如 Vmess和Vless 使用什么来运行，你可以选择 xray，或者sing-box。你可以点击后面的链接下载最新的 4.72-2版本
x86_64的 https://github.com/bcseputetto/Are-u-ok/releases/download/iStoreOS/PassWall_4.72-2_x86_64_all_sdk_22.03.6.run
aarch64，也就是ARM64的 https://github.com/bcseputetto/Are-u-ok/releases/download/iStoreOS/PassWall_4.72-2_aarch64_a53_all_sdk_22.03.6.run

**Comment by yunshenwuji** [comment]
> @yunshenwuji 在passwall上方的节点订阅设置里面，可以设定v2ray使用的两种协议，比如 Vmess和Vless 使用什么来运行，你可以选择 xray，或者sing-box。你可以点击后面的链接下载最新的 4.72-2版本 x86_64的 https://github.com/bcseputetto/Are-u-ok/releases/download/iStoreOS/PassWall_4.72-2_x86_64_all_sdk_22.03.6.run aarch64，也就是ARM64的 https://github.com/bcseputetto/Are-u-ok/releases/download/iStoreOS/PassWall_4.72-2_aarch64_a53_all_sdk_22.03.6.run

感谢您的解答，我这就快照下现有的iStoreOS虚拟机，然后尝试升级下passwall

**Comment by PauLmaX668** [comment]
现在才看到，感激不尽！

**Comment by yunshenwuji** [comment]
> 现在才看到，感激不尽！

我是passwall4.668直接覆盖安装了上面那位同学提供的 .run 包，安装完成后，先重置了一下passwall，然后 重启了下iStoreOS，然后按正常流程添加机场的订阅链接就搞定了
