### ISSUE TITLE
请求大佬更新passwall 4.73

### ISSUE THREAD

**Issue by PauLmaX668** [AUK9527/Are-u-ok#140]
刚刚登录github，发现passwall已经更新到4.73了，烦请大佬有空更新一下，万分感谢！

**Comment by bcseputetto** [comment]
这个仓库新版插件目前都是我提交的，但是需要等待AUK9527确认合并，着急可以先到我仓库里下，问题解决了请关闭issue

**Comment by PauLmaX668** [comment]
好的，期盼大佬早日更新4.73插件，我先关闭issue
