### ISSUE TITLE
passwall及passwall2负载均衡节点可用性超时问题

### ISSUE THREAD

**Issue by leekyy** [AUK9527/Are-u-ok#142]
插件：passwall,passwall2
istoreos版本：22.03.6 2024012613
版本：4.72
节点类型，trojan
现象：在负载均衡启用后，新建负载均衡节点配置完后节点延迟为0，但是可用性却是一直超时，同时也无法正常使用此节点。
我又尝试使用ios上的shadowsocket新建节点连接负载均衡的地址后，发现是可以正常使用的。
请问这是什么原因呢？
以下为passwall和shadowsocket的节点配置文件截图：

![image](https://github.com/AUK9527/Are-u-ok/assets/20851015/5e05a097-a3a4-49eb-a685-b3feb12084b6)

<img width="892" alt="image" src="https://github.com/AUK9527/Are-u-ok/assets/20851015/381c9325-73f1-428e-ae9e-9b7016dfcbc2">

**Comment by bcseputetto** [comment]
在passwall负载均衡的`健康检查类型`为`passwall 内置实现`时，新添加的节点请直接用 Socks指向负载均衡监听端口(比如类型Xray，协议Socks)直接地址`127.0.0.1`，端口`1181`，其余什么都不要即可。
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/5298aa5b-15c8-42a4-ba10-2db5625e39e7)
添加到负载均衡的节点不需要协议参数一致，添加的新节点也不需要原节点的参数。

**Comment by leekyy** [comment]
> 在passwall负载均衡的`健康检查类型`为`passwall 内置实现`时，新添加的节点请直接用 Socks指向负载均衡监听端口(比如类型Xray，协议Socks)直接地址`127.0.0.1`，端口`1181`，其余什么都不要即可。 ![image](https://private-user-images.githubusercontent.com/29139573/300954808-5298aa5b-15c8-42a4-ba10-2db5625e39e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjQ0MTcsIm5iZiI6MTcwNjY2NDExNywicGF0aCI6Ii8yOTEzOTU3My8zMDA5NTQ4MDgtNTI5OGFhNWItMTVjOC00MmE0LWJhMTAtMmRiNTYyNWUzOWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1M2U3YTM4Yzg5MmZiZWQyYWJmYjkzZDBlYTlkYWE2MjdhZTMwODA5ZjMyZTg0OTc3ZTI5NjA4NDhlZmE4ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9YPp9Cj0UuOGWU_zFM6_m5x78Y_-T-D5GLl9HYAuV8) 添加到负载均衡的节点不需要协议参数一致，添加的新节点也不需要原节点的参数。

可以了哈～感谢

**Comment by BIGIVAN** [comment]
> 在passwall负载均衡的`健康检查类型`为`passwall 内置实现`时，新添加的节点请直接用 Socks指向负载均衡监听端口(比如类型Xray，协议Socks)直接地址`127.0.0.1`，端口`1181`，其余什么都不要即可。 ![image](https://private-user-images.githubusercontent.com/29139573/300954808-5298aa5b-15c8-42a4-ba10-2db5625e39e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTY4MjMsIm5iZiI6MTcxNTMxNjUyMywicGF0aCI6Ii8yOTEzOTU3My8zMDA5NTQ4MDgtNTI5OGFhNWItMTVjOC00MmE0LWJhMTAtMmRiNTYyNWUzOWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA0NDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YjQzZjhiYzAyNjQyNGU0ZjQ4YTRjZjA2MDMwYzkzZDY0MjA4ZmRiMDRlODhhNmUyMDdkMDk3ZGRjYThjOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMIB9VTPG6tRrUFM3ICd8qE65eJAUZABRhyFG8BBsVI) 添加到负载均衡的节点不需要协议参数一致，添加的新节点也不需要原节点的参数。

thank you
