### ISSUE TITLE
可否用libopenssl3编译软件包

### ISSUE THREAD

**Issue by make126** [AUK9527/Are-u-ok#144]
发现GliNet路由器MT6000最新版把软件包libopenssl1.1升级到libopenssl3了，这样会导致AUK9527/Are-u-ok里面所有istore插件装不上报错runtime error，严重时甚至进不了openwrt。而在GliNet MT2500上没有这个问题，仔细查了一下MT2500最新版还是libopenssl1.1

可否考虑未来用libopenssl3编译软件包？

**Comment by bcseputetto** [comment]
等`iStoreOS`升级到23.05时会考虑，用`libopenssl1.1`而不是`libopenssl3` 不只是因为`iStoreOS`的问题。部分机场的SSR节点还在用已经被`libopenssl3`抛弃的加密算法，所以那些用户用了依赖`libopenssl3`的`shadowsocksr-libev`反而可能会无法使用他们机场的SSR节点
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/8cab9b7a-7cb3-4905-a774-603e13c042b9)
passwall的依赖中，依赖`libopenssl`的软件包有`shadowsocksr-libev-ssr-local` `shadowsocksr-libev-ssr-redir` `shadowsocksr-libev-ssr-server` 以及 `trojan-plus`
SSR-Plus的依赖中，依赖`libopenssl`的软件包有`shadowsocksr-libev-ssr-check` `shadowsocksr-libev-ssr-local` `shadowsocksr-libev-ssr-redir` `shadowsocksr-libev-ssr-server` 以及 `trojan`

___
如果问题已解决请关闭issue

**Comment by make126** [comment]
MT6000 v4.5.6最新固件恢复出厂设置后，正常安装istore，但是上传passwall最新固件时会报错：
Configuring xray-core.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for haproxy
 * pkg_hash_fetch_best_installation_candidate: Packages for haproxy found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package haproxy.
 * pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for shadowsocksr-libev-ssr-local
 * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-local found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-local.
 * pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for shadowsocksr-libev-ssr-redir
 * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-redir found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-redir.
 * pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for shadowsocksr-libev-ssr-server
 * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-server found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-server.
 * pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for trojan-plus
 * pkg_hash_fetch_best_installation_candidate: Packages for trojan-plus found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package trojan-plus.
Installing luci-app-passwall (4.73-3) to root...
Installing luci-i18n-passwall-zh-cn (git-24.032.30869-35a254d) to root...
Installing luci-app-passwall (4.73-3) to root...
Configuring luci-app-passwall.

卡在这一步不动了，然后刷新或重启路由后可以登陆路由，但进不了openwrt，报错：
Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: /usr/lib/lua/luci/passwall/api.lua:8: module 'luci.cbi.datatypes' not found:
no field package.preload['luci.cbi.datatypes']
no file './luci/cbi/datatypes.lua'
no file '/usr/share/lua/luci/cbi/datatypes.lua'
no file '/usr/share/lua/luci/cbi/datatypes/init.lua'
no file '/usr/lib/lua/luci/cbi/datatypes.lua'
no file '/usr/lib/lua/luci/cbi/datatypes/init.lua'
no file './luci/cbi/datatypes.so'
no file '/usr/lib/lua/luci/cbi/datatypes.so'
no file '/usr/lib/lua/loadall.so'
no file './luci.so'
no file '/usr/lib/lua/luci.so'
no file '/usr/lib/lua/loadall.so'
In error(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function build_pagetree (/usr/share/ucode/luci/dispatcher.uc:382:73)
  called from function menu_json (/usr/share/ucode/luci/dispatcher.uc:439:26)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:898:24)
  called from anonymous function (/www/cgi-bin/luci:39:13)
 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^

需要重置出厂设置才能恢复。感觉就是libopenssl版本问题造成，不知道怎么解决或者旁路掉？

**Comment by xuelei9300** [comment]
mt6000有openwpt官方固件吗？mt3600官方固件很好用发自我的 iPhone在 2024年2月12日，12:00，make126 ***@***.***> 写道：﻿
MT6000 v4.5.6最新固件恢复出厂设置后，正常安装istore，但是上传passwall最新固件时会报错：
Configuring xray-core.
Collected errors:

pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for haproxy
pkg_hash_fetch_best_installation_candidate: Packages for haproxy found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package haproxy.
pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for shadowsocksr-libev-ssr-local
pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-local found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-local.
pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for shadowsocksr-libev-ssr-redir
pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-redir found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-redir.
pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for shadowsocksr-libev-ssr-server
pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-server found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-server.
pkg_hash_check_unresolved: cannot find dependency libopenssl1.1 for trojan-plus
pkg_hash_fetch_best_installation_candidate: Packages for trojan-plus found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package trojan-plus.
Installing luci-app-passwall (4.73-3) to root...
Installing luci-i18n-passwall-zh-cn (git-24.032.30869-35a254d) to root...
Installing luci-app-passwall (4.73-3) to root...
Configuring luci-app-passwall.

卡在这一步不懂，重启路由后进不了openwrt了，报错：
Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: /usr/lib/lua/luci/passwall/api.lua:8: module 'luci.cbi.datatypes' not found:
no field package.preload['luci.cbi.datatypes']
no file './luci/cbi/datatypes.lua'
no file '/usr/share/lua/luci/cbi/datatypes.lua'
no file '/usr/share/lua/luci/cbi/datatypes/init.lua'
no file '/usr/lib/lua/luci/cbi/datatypes.lua'
no file '/usr/lib/lua/luci/cbi/datatypes/init.lua'
no file './luci/cbi/datatypes.so'
no file '/usr/lib/lua/luci/cbi/datatypes.so'
no file '/usr/lib/lua/loadall.so'
no file './luci.so'
no file '/usr/lib/lua/luci.so'
no file '/usr/lib/lua/loadall.so'
In error(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function ((tail call))
In anonymous function, file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
called from function build_pagetree (/usr/share/ucode/luci/dispatcher.uc:382:73)
called from function menu_json (/usr/share/ucode/luci/dispatcher.uc:439:26)
called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:898:24)
called from anonymous function (/www/cgi-bin/luci:39:13)
        return lcall.call(modname, method, ...args);
Near here ----------------------------------------^
感觉就是libopenssl版本问题造成。不知道怎么解决或者旁路掉？

**Comment by bcseputetto** [comment]
@make126 @xuelei9300 如果不是`iStoreOS`，是其它23.05及以上版本的OpenWrt，可以直接去`passwall`官方项目下载安装。
[x86_64依赖压缩包](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/passwall_packages_ipk_x86_64.zip)
[aarch64_a53依赖压缩包](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/passwall_packages_ipk_aarch64_cortex-a53.zip)
[luci-app-passwall_4.73-3](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/luci-23.05_luci-app-passwall_4.73-3_all.ipk)
[luci-i18n-passwall-zh-cn](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/luci-23.05_luci-i18n-passwall-zh-cn_git-24.032.30869-35a254d_all.ipk)

下载对应架构的依赖压缩包，解压出 ipk进行安装。
然后再安装 `luci-app`的ipk，再安装`luci-i18n`语言包的ipk
passwall官方项目是使用 `23.05`SDK进行编译的。

___
如果问题已解决请关闭issue

**Comment by make126** [comment]
> @make126 @xuelei9300 如果不是`iStoreOS`，是其它23.05及以上版本的OpenWrt，可以直接去`passwall`官方项目下载安装。 [x86_64依赖压缩包](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/passwall_packages_ipk_x86_64.zip) [aarch64_a53依赖压缩包](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/passwall_packages_ipk_aarch64_cortex-a53.zip) [luci-app-passwall_4.73-3](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/luci-23.05_luci-app-passwall_4.73-3_all.ipk) [luci-i18n-passwall-zh-cn](https://github.com/xiaorouji/openwrt-passwall/releases/download/4.73-3/luci-23.05_luci-i18n-passwall-zh-cn_git-24.032.30869-35a254d_all.ipk)
> 
> 下载对应架构的依赖压缩包，解压出 ipk进行安装。 然后再安装 `luci-app`的ipk，再安装`luci-i18n`语言包的ipk passwall官方项目是使用 `23.05`SDK进行编译的。
> 
> 如果问题已解决请关闭issue

多谢告知！按照你提供的方法，已经成功安装好passwall并丝滑运行，只是需要手动安装23个依赖。
