### ISSUE TITLE
SSR or Passwall 安装问题

### ISSUE THREAD

**Issue by yakjian** [AUK9527/Are-u-ok#146]
这个package的路径找不到
https://mirrors.aliyun.com/openwrt/releases/21.02.1/targets/friendlyelec/armv8/packages/Packages.gz

**Comment by bcseputetto** [comment]
@yakjian 官方没有 friendlyelec 这个 target，这个opkg软件源是不可用的，请自己修正opkg软件源
无论是 `21.02.1` 也好，还是最新稳定版的 `23.05.2` 均没有
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/40f58282-f533-489e-a1a5-166e39989e0a)
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/b70813a4-2f96-4f88-b4ec-fbafc9a8c6af)

___
如果问题解决了请关闭issue
