### ISSUE TITLE
passwall 分流chnlist是不是默认没有加载？...现在苹果 app store无法打开

### ISSUE THREAD

**Issue by lirui0215** [AUK9527/Are-u-ok#148]
版本4.74.1
配置及设置如图
![IMG_4706](https://github.com/AUK9527/Are-u-ok/assets/30290363/f3becf55-6cea-47aa-98f1-e0d6b53a725c)
![IMG_4707](https://github.com/AUK9527/Are-u-ok/assets/30290363/824cbbdf-48c9-4f7b-b572-1115c2cbb191)
![IMG_4708](https://github.com/AUK9527/Are-u-ok/assets/30290363/0bbf15a6-625d-42cf-953b-0fb5eb250e0a)
![IMG_4709](https://github.com/AUK9527/Are-u-ok/assets/30290363/d47e25b4-fd50-4bf8-a1d2-5ff828328c03)
![IMG_4705](https://github.com/AUK9527/Are-u-ok/assets/30290363/6c85ce1a-0e28-48ac-8aa5-6b8c0fe2f634)

**Comment by lirui0215** [comment]
装了smartdns接管了dnsmasq，问题好像解决了

**Comment by bcseputetto** [comment]
@lirui0215 
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/6653aa4c-fc1c-498a-beeb-a5b048270b4e)
这个中国列表就是 chnlist，chnlist你要走代理吗？还是你只是想让苹果服务走代理？
___
如果问题解决，请关闭issue

**Comment by lirui0215** [comment]
> @lirui0215 ![image](https://private-user-images.githubusercontent.com/29139573/307583025-6653aa4c-fc1c-498a-beeb-a5b048270b4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjA5NDAsIm5iZiI6MTcwODg2MDY0MCwicGF0aCI6Ii8yOTEzOTU3My8zMDc1ODMwMjUtNjY1M2FhNGMtZmMxYy00OThhLWJlZWItYTViMDQ4MjcwYjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDExMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjg5ZTFlYjNlNWM1NTFmZjU1ZmQzMzI3N2EzMjU0OTQ5MzM5MGViMGMwNjZlNGZhNzgzNDEyMWMxMjIyYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fs0iq3CMgizREmLEbgfii4Xw9-zZ0Tdh3qmVfP2KHmg) 这个中国列表就是 chnlist，chnlist你要走代理吗？还是你只是想让苹果服务走代理？
> 
> 如果问题解决，请关闭issue

苹果服务无法正常使用，无论是否打开

**Comment by bcseputetto** [comment]
@lirui0215 请到我仓库下载 4.74-4，更新后再看看
____
如果问题解决，请关闭issue
