### ISSUE TITLE
更新 a53 的 helloworld

### ISSUE THREAD

**Issue by qy2009** [AUK9527/Are-u-ok#164]
谢谢大佬啦！

**Comment by bcseputetto** [comment]
据我所知 helloworld(VSSR) 已经停止维护了，如果你知道 helloworld(VSSR) 哪里还有在维护，麻烦你贴一下项目的链接

**Comment by qy2009** [comment]
这个一直还在更新？ 
https://github.com/fw876/helloworld

**Comment by bcseputetto** [comment]
@qy2009  这个就是ssr-plus 而不是 vssr(helloworld)

**Comment by bcseputetto** [comment]
![image](https://github.com/AUK9527/Are-u-ok/assets/29139573/9fc1d873-56ed-42dc-b189-80eac4370047)
vssr(helloworld) 就是从 ssr+(ssrplus) 修改而来的，而你发的那个 helloworld项目，就是ssrplus
vssr(helloworld) 已经停止维护很久了

**Comment by qy2009** [comment]
晕。。知道了，谢谢啊！
现在的helloworld, 我一装上去，我的GLINET的路由器就登陆不了他自己的界面，但是从cgi-bin 还是可以登陆。所以不太敢用。
