### ISSUE TITLE
无法安装其他ipk插件

### ISSUE THREAD

**Issue by NUAA-W** [AUK9527/Are-u-ok#18]
为什么在其他地方下载的ipk文件安装不上。

正在上传插件
Unknown package 'luci-app-usb-printer'.

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency p910nd for luci-app-usb-printer
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-usb-printer found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-usb-printer.

离线安装失败,错误码 255

这是错误信息。安装这里的几个插件需要重启才会在服务中显示

**Comment by NUAA-W** [comment]
更新到最新版固件貌似可以安装了

**Comment by AUK9527** [comment]
> 更新到最新版固件貌似可以安装了

因为你之前 缺依赖，openwrt的插件 不是和手机app 一样，一个安装包就成，某些插件 是有依赖的，你依赖没，就装个壳子，怎么装？
