### ISSUE TITLE
增加 homeproxy 的编译

### ISSUE THREAD

**Issue by qy2009** [AUK9527/Are-u-ok#183]
这个最近好像是新的，想试试是不是比openclash更好。可以做一个编译嘛？ 谢谢啦

https://github.com/immortalwrt/homeproxy

https://www.youtube.com/watch?v=BAfbkLizFGc

**Comment by bcseputetto** [comment]
暂时不会做，参考下面的issue
https://github.com/bcseputetto/Are-u-ok/issues/2
https://github.com/istoreos/istoreos/issues/1664

**Comment by qy2009** [comment]
@bcseputetto  DAED 呢？ 感觉这个比sing-box更快？ 

https://github.com/QiuSimons/luci-app-daed
我试着直接用上面编译好的IPK，装不了，说incompatible..好像还缺了许多KMOD. 依赖
https://www.youtube.com/watch?v=tqzdQvYT61w&t=482s

**Comment by bcseputetto** [comment]
@qy2009 daed也是一样的，需要等以后
`kmod-xdp-sockets-diag` 的问题没法解决的，需要你从固件编译阶段就开始。且需要 23.05 分支以及之后的OpenWrt官方源码。
如果不使用 23.05 之后的OpenWrt官方源码，你就需要像 luci-app-daed 项目里面说的那样，对OpenWrt的源码做出修改才能支持

**Comment by qy2009** [comment]
明白了，谢谢啦！
