### ISSUE TITLE
增加 cloudflared 软件包

### ISSUE THREAD

**Issue by purainity** [AUK9527/Are-u-ok#189]
cloudflared 是 Cloudflare Tunnel 内网穿透的客户端，官方 iStore 中没有提供，请增加它的 .run 软件包

**Comment by bcseputetto** [comment]
`luci-i18n-cloudflared-zh-cn`
`luci-app-cloudflared`
`cloudflared`
这些软件包在 OpenWrt官方软件源里都有提供，你只需要安装 `luci-i18n-cloudflared-zh-cn`，剩下的两个软件包都会被安装，它们是依赖关系。没有必要专门提供 .run 软件包。
你可以在网页后台，系统-软件包里进行安装（如果可用软件包是空的，记得更新列表）
![QQ_1722003658155](https://github.com/user-attachments/assets/2fba0ece-43ea-4e2c-b937-b1c651fc3244)
![QQ_1722003672713](https://github.com/user-attachments/assets/75984bf2-2f7c-4277-83cf-e88d4eca23fa)

也可以在终端里面执行
```console
opkg update
#opkg软件包更新列表
opkg install luci-i18n-cloudflared-zh-cn
#安装软件包 luci-i18n-cloudflared-zh-cn 它的依赖luci-app-cloudflared和cloudflared会被自动安装
```

**Comment by purainity** [comment]
这里的软件包版本偏老啊，AList 和 cloudflared 都比最新的老好几个版本了，执行 `opkg update` 更新之后也只能获取到旧版本

**Comment by bcseputetto** [comment]
@jibukeshi 22.03.6是OpenWrt官方在2023年12月发布的，所以软件包也是在这个时间点编译的，发布后该分支软件源内的软件包版本基本就停留在编译的那个时间点左右的版本了，不需要什么都追新版本。对于内核模块来说这个软件源不能随便换，需要一一对应版本，否则无法安装。
目前22.03分支最新版本是 22.03.7，发布时间为 2024年7月22日。
___
OpenWrt官方旧稳定版(22.03)发布时间参考
22.03.0 2022年09月
22.03.1 2022年10月
22.03.2 2022年10月
22.03.3 2023年01月
22.03.4 2023年04月
22.03.5 2023年04月
22.03.6 2023年12月 ⬅️iStoreOS目前最新稳定版分支在这
22.03.7 2024年07月
___
OpenWrt官方新稳定版分支(23.05)发布时间参考
23.05.0 2023年10月
23.05.1 2023年11月
23.05.2 2023年11月
23.05.3 2024年03月
23.05.4 2024年07月

**Comment by airflowshu** [comment]
我现在用的就是你上面贴图的ipk版本，配置好后，cf后台提示版本老了哦。。。。

![Image](https://github.com/user-attachments/assets/f43788c6-53f4-468b-8f04-7e7a9021e4f3)

虽然功能不影响，但被官方后台提示隧道客户端版本有点老，总觉得不得劲，安全或者访问性能问题不知道受不受影响

我找到了一个别人编译好的x86的：https://openwrt.pkgs.org/24.10/openwrt-packages-x86_64/cloudflared_2025.2.1-r1_x86_64.ipk.html   但是上面显示基于OpenWrt 24.10，而我用的是23+   我也不敢更新

**Comment by purainity** [comment]
> 我现在用的就是你上面贴图的ipk版本，配置好后，cf后台提示版本老了哦。。。。
> 
> ![Image](https://github.com/user-attachments/assets/f43788c6-53f4-468b-8f04-7e7a9021e4f3)
> 
> 虽然功能不影响，但被官方后台提示隧道客户端版本有点老，总觉得不得劲，安全或者访问性能问题不知道受不受影响
> 
> 我找到了一个别人编译好的x86的：https://openwrt.pkgs.org/24.10/openwrt-packages-x86_64/cloudflared_2025.2.1-r1_x86_64.ipk.html 但是上面显示基于OpenWrt 24.10，而我用的是23+ 我也不敢更新

我的解决办法是替换二进制文件手动升级。
去 https://github.com/cloudflare/cloudflared/releases 下载最新的软件包，手动替换 `/usr/bin/cloudflared` 然后重启 cloudflared，接着就可以用 `cloudflared update` 命令升级了

**Comment by wanvfx** [comment]
现在是2025年5月，目前已稳定升级至 iStoreOS 24.10.1 2025052311 这个工具建议是时候启动了。
