### ISSUE TITLE
有没有istore内置的homebox内网测速的单独的AArch64的ipk插件包

### ISSUE THREAD

**Issue by x2287711259** [AUK9527/Are-u-ok#19]
有没有istore内置的homebox内网测速的单独的AArch64的ipk插件包

**Comment by x2287711259** [comment]
N1盒子可以直接安装的

**Comment by AUK9527** [comment]
> N1盒子可以直接安装的
[homebox.zip](https://github.com/AUK9527/Are-u-ok/files/8694211/homebox.zip)

常理是不会提供这些的，看着简单，提供下，后续要啥单独的插件，自己去找源码吧。

**Comment by x2287711259** [comment]
谢谢，没有基础不太会弄，网上看了一些单独编译ipk插件的教程，还是不太会，一知半解
