### ISSUE TITLE
网易云解锁安装错误

### ISSUE THREAD

**Issue by longaga** [AUK9527/Are-u-ok#20]
![$7F)W}H(FFG7`FR(IF$ $85](https://user-images.githubusercontent.com/25930270/168456640-f2400498-fe2c-4576-9344-46f1adf8f471.png)

如题

**Comment by HiJwm** [comment]
同样问题

**Comment by AUK9527** [comment]
> 同样问题

x86的吧，麻烦提问，说平台，这里有x86和a53的。不说平台的，不是太想看。
