### ISSUE TITLE
Cannot install package luci-i18n-passwall2-zh-cn.

### ISSUE THREAD

**Issue by mimimiaomiao1** [AUK9527/Are-u-ok#206]
Cannot install package luci-i18n-passwall2-zh-cn.

**Comment by RyanL1nk** [comment]
我也遇到了这个问题，怎么解决啊

**Comment by mimimiaomiao1** [comment]
> 我也遇到了这个问题，怎么解决啊

我换了一个包然后解决了，好像是x86还是什么x64的。装好以后我也没用旁路有了。费劲。
