### ISSUE TITLE
【重要提醒】由于KoolCenter软件中心服务器备案问题导致软件包无法安装的临时解决办法

### ISSUE THREAD

**Issue by bcseputetto** [AUK9527/Are-u-ok#207]
由于KoolCenter部分域名备案丢失，导致本项目软件包在更新软件源时会遇到KoolCenter软件源连接失败后，判断软件源更新失败而终止脚本的问题。在这里提供两个解决办法。
**解决办法二选一即可**
**解决办法二选一即可**
**解决办法二选一即可**

1. 使用网页终端(ttyd)或者ssh连上后执行以下命令修复iStore【推荐】
```
sh -c "$(curl -sSL https://fw.koolcenter.com/iStoreOS/alpha/fix-istore.sh)"
```
该命令会将iStore以及软件源切换到新的域名，切换后在iStore维护更新iStore版本到最新的`0.1.26-3`

2. 打开路由器网页后台，来到【系统】-【软件包】-【配置OPKG】
![1731404743821](https://github.com/user-attachments/assets/ad590c3b-0f38-4cef-acac-2488375712a3)
将第二个框的软件源，最前面加一个`#` 把这个软件源先注释掉，保存。然后再尝试本项目软件包的安装。
安装完后就可以取消注释了，或者你也可以等KoolCenter的域名备案完毕后再取消注释，当然为了你不会忘记取消注释，还是建议你安装完软件包后立即取消注释，否则影响后续iStore应用商店的使用

**Comment by mipaers** [comment]
我就说安装办法都是失败.哈哈

**Comment by imdvpt** [comment]
没有这一行，无法正常安装

**Comment by imdvpt** [comment]
-rw-r--r--    1 root     root      19357324 Nov 15 18:05 /tmp/is-root/tmp/OpenClash_0.46.014+aarch_64_core (1).run
9fd09445f564582ddff4e3a24bfd2211  /tmp/is-root/tmp/OpenClash_0.46.014+aarch_64_core (1).run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing luci-app-openclash_with_clash_core  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
*** Failed to download the package list from https://istore.linkease.com/repo/all/compat/Packages.gz

Downloading http://mirrors.pku.edu.cn/immortalwrt/releases/21.02.1/packages/aarch64_generic/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading http://mirrors.pku.edu.cn/immortalwrt/releases/packages-18.06-k5.4/aarch64_generic/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading http://mirrors.pku.edu.cn/immortalwrt/releases/21.02.1/packages/aarch64_generic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading http://mirrors.pku.edu.cn/immortalwrt/releases/21.02.1/packages/aarch64_generic/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading http://mirrors.pku.edu.cn/immortalwrt/releases/21.02.1/packages/aarch64_generic/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Collected errors:
 * opkg_download: Failed to download https://istore.linkease.com/repo/all/compat/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源。

**Comment by bcseputetto** [comment]
> opkg_download: Failed to download https://istore.linkease.com/repo/all/compat/Packages.gz, wget returned 4.

@imdvpt 没看到这个吗？就是这个源连不上，就是要解决先不用这个源。

**Comment by gang1974** [comment]
还是等备案完成再弄吧，提供的 2 种方法安装 SSR 都是出错。

**Comment by bcseputetto** [comment]
> 还是等备案完成再弄吧，提供的 2 种方法安装 SSR 都是出错。

@gang1974 提供报错内容

**Comment by gang1974** [comment]
> > 还是等备案完成再弄吧，提供的 2 种方法安装 SSR 都是出错。
> 
> @gang1974 提供报错内容

![001](https://github.com/user-attachments/assets/7feb221f-37af-4558-a881-08f5c6246f60)

**Comment by bcseputetto** [comment]
@gang1974 你这什么机器？什么CPU？

**Comment by gang1974** [comment]
> @gang1974 你这什么机器？什么CPU？

不好意思，是我弄错安装包了。

**Comment by sonyNEXTgen** [comment]
![QQ截图20241123235945](https://github.com/user-attachments/assets/3cc98345-6f8c-4b35-97c5-ea3537254187)
大佬，执行您的脚本都有报错怎么办？这个输出符合预期吗？执行完可以升级到0.1.26-3了，但是再上传本项目的.run包，还是报错，提示更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源

**Comment by bcseputetto** [comment]
> ![QQ截图20241123235945](https://private-user-images.githubusercontent.com/174285435/389209619-3cc98345-6f8c-4b35-97c5-ea3537254187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzg2ODgsIm5iZiI6MTczMjM3ODM4OCwicGF0aCI6Ii8xNzQyODU0MzUvMzg5MjA5NjE5LTNjYzk4MzQ1LTZmOGMtNGIzNS05N2M1LWVhMzUzNzI1NDE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxNjEzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTIxOTNiZGNkNmNmN2Q0ZjVlMzgyMWY0NTRhNzgwMWQzYmQ0M2QzNGQxYWY2N2M1Y2Q1ZTA5OWExMjJiOTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TOVd6C2g3549cT-3G4CrR3MXozVUkiw-u39ShtAsF6Q) 大佬，执行您的脚本都有报错怎么办？这个输出符合预期吗？执行完可以升级到0.1.26-3了，但是再上传本项目的.run包，还是报错，提示更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源

@sonyNEXTgen 你的问题不是 KoolCenter的源不能连接，这个Issue提供的办法主要是解决 KoolCenter的源不能连接
从报错的信息就可以看出，你是 `mirrors.cernet.edu.cn` 这个高校联合镜像源不能连接
请你去iStoreOS首页，软件源配置，更换其他的高校源再试试

**Comment by zjuhippy** [comment]
Merlin固件有么有解决方案？

**Comment by sonyNEXTgen** [comment]
> > ![QQ截图20241123235945](https://private-user-images.githubusercontent.com/174285435/389209619-3cc98345-6f8c-4b35-97c5-ea3537254187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzg2ODgsIm5iZiI6MTczMjM3ODM4OCwicGF0aCI6Ii8xNzQyODU0MzUvMzg5MjA5NjE5LTNjYzk4MzQ1LTZmOGMtNGIzNS05N2M1LWVhMzUzNzI1NDE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxNjEzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTIxOTNiZGNkNmNmN2Q0ZjVlMzgyMWY0NTRhNzgwMWQzYmQ0M2QzNGQxYWY2N2M1Y2Q1ZTA5OWExMjJiOTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TOVd6C2g3549cT-3G4CrR3MXozVUkiw-u39ShtAsF6Q)大佬，执行您的脚本有报错怎么办？这个输出符合预期吗？执行完就可以升级到0.1.26-3了，但是再上传本项目的.run包，还是报错，提示更新软件源列表错误，请检查路由器自身网络连接以及是否有故障的软件源
> 
> @sonyNEXTgen的问题不是KoolCenter的源无法连接，这个问题提供的解决办法主要是解决KoolCenter的源无法连接， 从报错的信息就可以看出，你是`mirrors.cernet.edu.cn`本高校联合镜像源无法连接 请你去iStoreOS首页，软件源配置、更换其他高校源再尝试

修改软件源之后可以了，感谢大佬指点

**Comment by bcseputetto** [comment]
> Merlin固件有么有解决方案？

@zjuhippy 没有，华硕官改和梅林改版的软件中心只能等待KoolCenter备案完成。无法提前解决，不过华硕路由器的软件中心就算不能在线安装插件，离线的梯子插件应该是可以装的

**Comment by raimanfang** [comment]
-rwxr-xr-x    1 root     root      41819287 Nov 26 21:35 /tmp/is-root/tmp/SSR-Plus_188_aarch64_a53_all_sdk_22.03.7.run
c2ee116c600321699f0bdc8fe2509676  /tmp/is-root/tmp/SSR-Plus_188_aarch64_a53_all_sdk_22.03.7.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing ssrp_188_with_sdk_22.03.7_libopenssl1.1  100%  
Downloading https://istore.istoreos.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.istoreos.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/base/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/routing/Packages.gz
curl: (28) Failed to connect to mirrors.tuna.tsinghua.edu.cn port 443 after 10002 ms: Timeout was reached
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/routing/Packages.gz

Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/telephony/Packages.gz
curl: (28) Failed to connect to mirrors.tuna.tsinghua.edu.cn port 443 after 10002 ms: Timeout was reached
*** Failed to download the package list from https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/telephony/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/routing/Packages.gz, curl returned 28.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/telephony/Packages.gz, curl returned 28.
 * opkg_download: Check your network settings and connectivity.

更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源。

**Comment by bcseputetto** [comment]
@raimanfang 你的问题在上面也已经提到过了，注意看英文部分的报错信息，你是两条 `mirrors.tsinghua.edu.cn`的源没连上，再试试，或者去首页软件源配置换其他镜像源再试
本Issue是为了解决KoolCenter自己的源无法连接，KoolCneter自己的源是`istore.linkease.com`，以及`istore.istoreos.com`
