### ISSUE TITLE
下载软件包时找不到地址！

### ISSUE THREAD

**Issue by yishan2019** [AUK9527/Are-u-ok#208]
找不到 raw.githubusercontent.com 的服务器 IP 地址。

**Comment by bcseputetto** [comment]
@yishan2019 这是你梯子客户端规则问题，你梯子客户端没有让 `raw.githubusercontent.com`这个域名走代理，所以没有用正确的DNS去解析它，可不就是连不上无法下载，这是你和github的连接问题，跟项目没有关系

**Comment by yishan2019** [comment]
刚才加入了这个地址走代理，还是找不到地址！

bcseputetto ***@***.***> 于2024年11月16日周六 17:56写道：

**Comment by bcseputetto** [comment]
@yishan2019 你用的是什么梯子客户端？暂时切到全局模式试试，再不济换个客户端再看下，就是要解决你无法访问那个域名的问题

**Comment by yishan2019** [comment]
passwall


bcseputetto ***@***.***>于2024年11月16日 周六18:16写道：

**Comment by yishan2019** [comment]
我电脑上直接装了v2rayN都试过了也不行

张果冻 ***@***.***>于2024年11月16日 周六18:17写道：

**Comment by yishan2019** [comment]
以前我可以的，这次就不行了

张果冻 ***@***.***>于2024年11月16日 周六18:19写道：

**Comment by bcseputetto** [comment]
这不是项目能够帮你解决的，重点还是你和github的连接问题，你可以连接`github.com` 但不能连接`githubusercontent.com`

**Comment by yishan2019** [comment]
反复用苹果手机走流量，用小火箭开的全局，还是打不开链接和这个地址，应该是它的网站出问题了

bcseputetto ***@***.***>于2024年11月16日 周六18:23写道：

**Comment by bcseputetto** [comment]
https://github.com/user-attachments/assets/a391a659-8d72-4d36-8dc2-26f2e36ccb7e

是你的问题，请看此录像。可以正常下载

**Comment by yishan2019** [comment]
这个极有可能是防火墙把这个地址单独列进黑名单了，这是防火墙的新功能，所以你在墙外可以下载，但墙内怎么翻墙也访问不了，所以只能增加备用地址了。

bcseputetto ***@***.***>于2024年11月16日 周六18:50写道：

**Comment by yishan2019** [comment]
还有人的安卓机顶盒被列进去了无论如何翻墙这个机顶盒也看不了油管了！

张果冻 ***@***.***>于2024年11月16日 周六19:29写道：

**Comment by yishan2019** [comment]
这个网站太引人关注，所以被单独照顾了。

张果冻 ***@***.***>于2024年11月16日 周六19:32写道：

**Comment by bcseputetto** [comment]
@yishan2019 不在墙外，你为什么会认为在墙外，大概率就是你DNS问题，没有正常通过代理向海外DNS查询这个域名，这个域名在国内DNS是受到污染的

**Comment by yishan2019** [comment]
谢谢提示，在passwall里重新设置了一下DNS模式可以了，但是 openclash如何单独设置DNS还没想好

bcseputetto ***@***.***> 于2024年11月16日周六 20:04写道：

**Comment by bcseputetto** [comment]
@yishan2019 解决了，记得关闭这个issue
