### ISSUE TITLE
离线安装失败

### ISSUE THREAD

**Issue by zhouyunjian** [AUK9527/Are-u-ok#24]
正在上传插件
-rw-r--r--    1 root     root       8436338 Jun  5 10:02 /tmp/is-root/tmp/SSR-Plus_x86.run
8055c38b306e61044890f1a18ef7d315  /tmp/is-root/tmp/SSR-Plus_x86.run
Verifying archive integrity... All good.
Uncompressing OneClick install
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_koolshare_router_core
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_koolshare_router_base
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_koolshare_router_luci
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_koolshare_router_packages
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_koolshare_router_routing
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_koolshare_router_telephony
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Package dns2socks (2.1-2) installed in root is up to date.
Package ipt2socks (1.1.3-2) installed in root is up to date.
Package libudns (0.4-1) installed in root is up to date.
Package luci-app-ssr-plus (185-2) installed in root is up to date.
Package luci-i18n-ssr-plus-zh-cn (185-2) installed in root is up to date.
Package microsocks (1.0.3-1) installed in root is up to date.
Package pdnsd-alt (1.2.9b-par-3) installed in root is up to date.
Package redsocks2 (0.67-4) installed in root is up to date.
Package shadowsocksr-libev-ssr-check (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-server (2.5.6-9) installed in root is up to date.
Package simple-obfs (0.0.5-1) installed in root is up to date.
Package tcping (0.3-1) installed in root is up to date.
Package xray-core (1.5.6-1) installed in root is up to date.

     0%    49%    99%  100%   MD5 checksums are OK.     0%    49%    99%  100%  Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nf-log
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-ipt-ipset
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nf-conntrack-netlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nf-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-ipt-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-nf-tproxy
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.115-1-34826bde6d6a4ca2af33dd35276b60f4) for kmod-ipt-tproxy
Error loading shared library libmbedcrypto.so.3: No such file or directory (needed by /koolshare/bin/ss-local)
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_update: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_free: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_auth_decrypt: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_setkey: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_finish: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_hmac: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_hmac_starts: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_reset: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_hmac_update: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md5_ret: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_starts: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_update: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_set_iv: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_get_size: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_init: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_setup: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_setup: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_free: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_info_from_string: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_hmac_finish: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_cipher_auth_encrypt: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_info_from_string: symbol not found
Error relocating /koolshare/bin/ss-local: mbedtls_md_init: symbol not found
ln: libmbedcrypto.so.3: File exists
ln: libmbedcrypto.so.7: File exists

离线安装失败,错误码 1

**Comment by AUK9527** [comment]
装ss套件失败，你这不算是openwrt固件吧，用的 KoolShare LEDE那个高度定制的固件吧。那个固件就别尝试了，有些东西不一样 不一定通用。

**Comment by zhouyunjian** [comment]
是的，好吧，谢谢回复！
