### ISSUE TITLE
r2s最新istore离线安装失败

### ISSUE THREAD

**Issue by kid-oh** [AUK9527/Are-u-ok#25]
试了kms、passwall、ssrp都安装不了，刷新网页和换浏览器登录也没有出来，应该不是浏览器缓存问题

...............
-rw-r--r--    1 root     root       9385328 Jun 10 17:47 /tmp/is-root/tmp/PassWall_a53.run
472c1c5901e5595dfdec45f728dd37fe  /tmp/is-root/tmp/PassWall_a53.run
Verifying archive integrity... All good.
Uncompressing OneClick install
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/targets/rockchip/armv8/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
     0%    44%    89%  100%   MD5 checksums are OK.     0%    44%    89%  100%  Segmentation fault
-rw-r--r--    1 root     root       9385328 Jun 10 17:47 /tmp/is-root/tmp/PassWall_a53.run
472c1c5901e5595dfdec45f728dd37fe  /tmp/is-root/tmp/PassWall_a53.run
Verifying archive integrity... All good.
Uncompressing OneClick install
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/targets/rockchip/armv8/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony

     0%    44%    89%  100%   MD5 checksums are OK.     0%    44%    89%  100%  Segmentation fault
Error loading shared library libmbedcrypto.so.3: No such file or directory (needed by /usr/bin/ss-local)
Error relocating /usr/bin/ss-local: mbedtls_cipher_update: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_free: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_auth_decrypt: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_setkey: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_finish: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_hmac: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_hmac_starts: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_reset: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_hmac_update: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md5_ret: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_starts: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_update: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_set_iv: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_get_size: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_init: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_setup: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_setup: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_free: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_info_from_string: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_hmac_finish: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_cipher_auth_encrypt: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_info_from_string: symbol not found
Error relocating /usr/bin/ss-local: mbedtls_md_init: symbol not found
ln: libmbedcrypto.so.3: File exists

离线安装成功，请关闭当前窗口

**Comment by CHAOS0032** [comment]
同，手动安装open clash 后在服务列无法找到，能否尽快修复这个bug

**Comment by AUK9527** [comment]
> 

最下面 提示 安装成功后，如果你找不到， 先在 软件包里 看看 有木有，可能是浏览器缓存，再一个你是个啥平台，说简单点，啥机器

**Comment by AUK9527** [comment]
> Error relocating /usr/bin/ss-local: mbedtls_cipher_update: symbol not found

你这 看着就是ss 相关的 出错了，软件包里卸载shadowsocks所有相关的，再安装，看最终安装成功没。kms这个插件 又没特殊依赖，怎么存在不成功呢

**Comment by AUK9527** [comment]
你们不是iStoreOS固件 还是 就一般的openwrt 然后带的iStore？

**Comment by AUK9527** [comment]
> 试了kms、passwall、ssrp都安装不了，刷新网页和换浏览器登录也没有出来，应该不是浏览器缓存问题
> 
> ............... -rw-r--r-- 1 root root 9385328 Jun 10 17:47 /tmp/is-root/tmp/PassWall_a53.run 472c1c5901e5595dfdec45f728dd37fe /tmp/is-root/tmp/PassWall_a53.run Verifying archive integrity... All good. Uncompressing OneClick install Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/targets/rockchip/armv8/packages/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_core Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/base/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_base Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/luci/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_luci Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/packages/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_packages Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/routing/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_routing Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/telephony/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_telephony 0% ������� 44% ������� 89% ������� 100% MD5 checksums are OK. 0% ������� 44% ������� 89% ������� 100% Segmentation fault -rw-r--r-- 1 root root 9385328 Jun 10 17:47 /tmp/is-root/tmp/PassWall_a53.run 472c1c5901e5595dfdec45f728dd37fe /tmp/is-root/tmp/PassWall_a53.run Verifying archive integrity... All good. Uncompressing OneClick install Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/targets/rockchip/armv8/packages/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_core Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/base/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_base Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/luci/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_luci Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/packages/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_packages Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/routing/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_routing Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/telephony/Packages.gz Updated list of available packages in /var/opkg-lists/openwrt_telephony
> 
> ```
>  0% �������   44% �������   89% ������� 100%   MD5 checksums are OK.     0% �������   44% �������   89% ������� 100%  Segmentation fault
> ```
> 
> Error loading shared library libmbedcrypto.so.3: No such file or directory (needed by /usr/bin/ss-local) Error relocating /usr/bin/ss-local: mbedtls_cipher_update: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_free: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_auth_decrypt: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_setkey: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_finish: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_hmac: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_hmac_starts: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_reset: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_hmac_update: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md5_ret: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_starts: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_update: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_set_iv: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_get_size: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_init: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_setup: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_setup: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_free: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_info_from_string: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_hmac_finish: symbol not found Error relocating /usr/bin/ss-local: mbedtls_cipher_auth_encrypt: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_info_from_string: symbol not found Error relocating /usr/bin/ss-local: mbedtls_md_init: symbol not found ln: libmbedcrypto.so.3: File exists
> 
> 离线安装成功，请关闭当前窗口

如果是iStoreOS的固件，r2s应该是可以装a53的离线包，如果是其他人做的固件，有可能没做好兼容，这个需要固件作者的适配。

你r2s任何离线包都装不了，应该是用的别人做的openwrt+iStore的固件，没做好兼容，所以不能安装离线包，应该iStore商店里的包，你也装不了。

**Comment by xiangfeidexiaohuo** [comment]
> 同，手动安装open clash 后在服务列无法找到，能否尽快修复这个bug

你如果 能安装其他离线包或者iStore里的插件，只是安装passwall、ssr-p这几个插件报错ss相关，可以去装针对这种错误的专属包。

**Comment by AUK9527** [comment]
> 同，手动安装open clash 后在服务列无法找到，能否尽快修复这个bug

你如果 能安装其他离线包或者iStore里的插件，只是安装passwall、ssr-p这几个插件报错ss相关，可以去装针对这种错误的专属包。已经测试过没问题了。
