### ISSUE TITLE
安装passwal失败，段错误

### ISSUE THREAD

**Issue by msz1412** [AUK9527/Are-u-ok#26]
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/21.02.2/packages/aarch64_generic/telephony/Packages.sig
Signature check passed.

     0%    44%    89%  100%   MD5 checksums are OK.     0%    44%    89%  100%  Segmentation fault

**Comment by AUK9527** [comment]
这个错误 无所谓的啊，只要 passwall出现了 就成
