### ISSUE TITLE
MosDNS 启动报错

### ISSUE THREAD

**Issue by longaga** [AUK9527/Are-u-ok#28]
![9%D$7)TA8I8I7H1)O`0Y$G](https://user-images.githubusercontent.com/25930270/173721606-8ff823ae-bd05-4a1b-b38f-c24f767063ba.png)
如题，固件版本OpenWrt 21.02.2 2022061019，还原重装安装也出现这个问题

**Comment by AUK9527** [comment]
> ![9%D$7)TA8I8I7H1)O`0Y$G](https://user-images.githubusercontent.com/25930270/173721606-8ff823ae-bd05-4a1b-b38f-c24f767063ba.png) 如题，固件版本OpenWrt 21.02.2 2022061019，还原重装安装也出现这个问题

怎么说呢，你反馈错地方了。

这里只是管插件能安装呀，只是编译好插件打包，安装没问题。

至于这个插件有啥问题，出啥错，你要反馈给做写这款插件的大佬 https://github.com/sbwml/luci-app-mosdns

或者是你没更新数据库，或者是某fq插件有冲突等。
