### ISSUE TITLE
iStoreOSx86 passwall节点订阅120个会卡

### ISSUE THREAD

**Issue by dsyo2008** [AUK9527/Are-u-ok#29]
点节点卡几秒恢复好了
https://dd-static.jd.com/ddimg/jfs/t1/9793/8/17665/1269913/62b3302dE63b81f92/470b96a2ad21d67b.gif
麻烦下次能不带Trojan-Go？我VPS自架Trojan-Go，发现用不了，没法更新。囧半天找了借朋友梯子更新好了。

**Comment by AUK9527** [comment]
> Trojan-Go

Trojan早就去掉， 你还是用的老版本的离线包吧，重新下载。
