### ISSUE TITLE
求更新UnblockNeteaseMusic_a53以及Turbo ACC~~感谢

### ISSUE THREAD

**Issue by calonye** [AUK9527/Are-u-ok#37]
求更新UnblockNeteaseMusic_a53以及Turbo ACC~~感谢

**Comment by isoulgh** [comment]
同求Turbo ACC

**Comment by AUK9527** [comment]
UnblockNeteaseMusic 这个玩意没啥好更新的吧，看了下版本，也没更新个什么东西。

至于turboacc，跑错边了吧，turboacc是固态带的，和固件里的内核什么的深度绑定的，和离线包不搭边，没一毛钱的关系。
turboacc 这玩意又没啥好更新的，说真的，东西还是那些，具体是啥版，取决于固件作者。让第三方更新，想多了。

**Comment by AUK9527** [comment]
> 同求Turbo ACC

这个东西看固件作者，和第三方没任何关系。
