### ISSUE TITLE
hello world not working 

### ISSUE THREAD

**Issue by lucifer662607004** [AUK9527/Are-u-ok#4]
hello world无法运行
日志上看是依赖的/usr/sbin/trojan的动态库找不到：

root@ARS2:~# trojan --version
Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan)
Error loading shared library libboost_program_options.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan)
Error relocating /usr/sbin/trojan: _ZNK5boost15program_options29value_semantic_codecvt_helperIcE5parseERNS_3anyERKSt6vectorISsSaISsEEb: symbol not found
Error relocating /usr/sbin/trojan: _ZTIN5boost15program_options29value_semantic_codecvt_helperIcEE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_optionslsERSoRKNS0_19options_descriptionE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options11to_internalERKSs: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options6detail7cmdline3runEv: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options3argE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options13variables_mapC1Ev: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options8validateERNS_3anyERKSt6vectorISsSaISsEEPSsi: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options19options_descriptionC1ERKSsjj: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options6notifyERNS0_13variables_mapE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options19options_description21m_default_line_lengthE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options6detail7cmdline23set_options_descriptionERKNS0_19options_descriptionE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options30positional_options_description3addEPKci: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options19options_description11add_optionsEv: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options11bool_switchEPb: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options6detail7cmdline27get_canonical_option_prefixEv: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options30positional_options_descriptionC1Ev: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options6detail7cmdlineC2ERKSt6vectorISsSaISsEE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options6detail7cmdline22set_positional_optionsERKNS0_30positional_options_descriptionE: symbol not found
Error relocating /usr/sbin/trojan: _ZTVN5boost15program_options13variables_mapE: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options5storeERKNS0_20basic_parsed_optionsIcEERNS0_13variables_mapEb: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options29options_description_easy_initclEPKcS3_: symbol not found
Error relocating /usr/sbin/trojan: _ZN5boost15program_options29options_description_easy_initclEPKcPKNS0_14value_semanticES3_: symbol not found

看了下passwall的依赖是trojan-go，所以可以正常运行

**Comment by AUK9527** [comment]
或许安装的时候 缺了，trojan这玩意可以干掉了 不需要这玩意

更新过了，已经剔除掉trojan了

你可以试试新的

**Comment by lucifer662607004** [comment]
> 或许安装的时候 缺了，trojan这玩意可以干掉了 不需要这玩意
> 
> 更新过了，已经剔除掉trojan了
> 
> 你可以试试新的

我还是运行不了
2022-04-13 14:24:34 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动!
2022-04-13 14:20:06 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动!
2022-04-13 14:19:28 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动!

饿，意思是无法再使用trojan了是吗？因为我所有节点都是trojan的……😂

看了下依赖的boost是1.76的，而本地的boost库似乎是1.71的：

boost | 1.71.0-6

**Comment by AUK9527** [comment]
> > 或许安装的时候 缺了，trojan这玩意可以干掉了 不需要这玩意
> > 更新过了，已经剔除掉trojan了
> > 你可以试试新的
> 
> 我还是运行不了 2022-04-13 14:24:34 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动! 2022-04-13 14:20:06 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动! 2022-04-13 14:19:28 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动!
> 
> 饿，意思是无法再使用trojan了是吗？因为我所有节点都是trojan的……😂
> 
> 看了下依赖的boost是1.76的，而本地的boost库似乎是1.71的：
> 
> boost | 1.71.0-6

xray 就能运行trojan啊

**Comment by lucifer662607004** [comment]
> > > 或许安装的时候 缺了，trojan这玩意可以干掉了 不需要这玩意
> > > 更新过了，已经剔除掉trojan了
> > > 你可以试试新的
> > 
> > 
> > 我还是运行不了 2022-04-13 14:24:34 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动! 2022-04-13 14:20:06 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动! 2022-04-13 14:19:28 Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /usr/sbin/trojan) 4 线程 已启动!
> > 饿，意思是无法再使用trojan了是吗？因为我所有节点都是trojan的……😂
> > 看了下依赖的boost是1.76的，而本地的boost库似乎是1.71的：
> > boost | 1.71.0-6
> 
> xray 就能运行trojan啊

可是hello world并不能建立xray节点
