### ISSUE TITLE
ARS2安装解锁网易云音乐包失败

### ISSUE THREAD

**Issue by suyu0925** [AUK9527/Are-u-ok#40]
ARS2系统版本是`OpenWrt 21.02.3 r16765-5420d24037 / LuCI istoreos-21.02 branch git-22.200.22754-37fc9d6`，

手动安装UnblockNeteaseMusic_a53提示：

![image](https://user-images.githubusercontent.com/7429906/187030793-39d61f74-d404-4847-9b3a-51c13ddbc6ba.png)

**Comment by AUK9527** [comment]
没关系，你看看 服务里 已经有插件了

**Comment by stkroot** [comment]
这个不好用，怎么删除？因为安装失败，在软件包里面搜索不到
