### ISSUE TITLE
请问hello world 导入vmess导不进去，还有卸载这个插件怎么卸载啊

### ISSUE THREAD

**Issue by sooway** [AUK9527/Are-u-ok#43]
请问hello world 导入vmess导不进去，还有卸载这个插件怎么卸载啊，刚开始安装是失败的，但是在服务下有了这个插件了，后来又装了几次，装成功了，但是导入vmess导不进去，然后就行卸了重装，请问怎么卸载啊

**Comment by AUK9527** [comment]
搜vssr
