### ISSUE TITLE
请求加入支持naiveproxy的插件

### ISSUE THREAD

**Issue by iiidcc** [AUK9527/Are-u-ok#48]
如题

**Comment by LeiD215** [comment]
请求增加passwall2，据说这个支持NAIVEPROXY

**Comment by AUK9527** [comment]
不需要passwall2 啊，passwall 直接加上naiveproxy依赖就成。

**Comment by strive1216** [comment]
@AUK9527 使用了两天了 但是时不时超时连不上 ，重启又正常，这是怎么回事呢？
