### ISSUE TITLE
请求加入两个功能插件，CPU调频（cpufreq）、内存释放

### ISSUE THREAD

**Issue by jaychin2** [AUK9527/Are-u-ok#49]
请求加入两个功能插件，CPU调频（cpufreq）、内存释放
CPU调频插件
https://openwrt.pkgs.org/21.02/openwrt-packages-x86_64/collectd-mod-cpufreq_5.12.0-10_x86_64.ipk.html
有的喜欢节能，有的喜欢性能，有的喜欢按需，我觉得应该让用户自己选择。我是物理机，BIOS无法改频，因此非常需要

内存释放的功能

**Comment by qian9008** [comment]
这个不是原商店就有吗！！

**Comment by jaychin2** [comment]
> 这个不是原商店就有吗！！

调频，不是限制应用。arm有x86没有

**Comment by jaychin2** [comment]
![Screenshot_20221104_210419_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/94214687/199979144-a61427b4-8b4e-4d0d-a528-dc9f1b466f40.jpg)
就是这个插件，x86的固件没有。

**Comment by jaychin2** [comment]
https://github.com/gw826943555/openwrt-cpufreq
找到一个未汉化的，19.07使用的。
不知能否提供参考

**Comment by AUK9527** [comment]
这个东西要适配的， 不是单独的插件就能咋样的，所以这个东西还是要固件本身自带适配。x86无这个东西。
