### ISSUE TITLE
UnblockNeteaseMusic这个插件怎么卸载

### ISSUE THREAD

**Issue by coolyzp** [AUK9527/Are-u-ok#5]
UnblockNeteaseMusic这个插件怎么卸载

**Comment by HiJwm** [comment]
有这个插件吗?怎么看不到

**Comment by AUK9527** [comment]
> UnblockNeteaseMusic这个插件怎么卸载

软件包里  就搜你 说的这个啊   unblock  music等

**Comment by coolyzp** [comment]
> 
真的搜不到，能搜到我就不问了

**Comment by coolyzp** [comment]
> > UnblockNeteaseMusic这个插件怎么卸载
> 
> 软件包里 就搜你 说的这个啊 unblock music等

真的搜不到，能搜到我就不问了

**Comment by stkroot** [comment]
同问，安装后不能删除，软件包里面搜索不到
