### ISSUE TITLE
AdGuardHome 和OpenClash插件建议把核心也带上，做到下载后配置即可用。

### ISSUE THREAD

**Issue by bluesyk** [AUK9527/Are-u-ok#50]
**必现问题，无需日志，当前下载是X86平台的插件。**

**当前AdGuardHome和OpenClash的插件安装后不能马上就用，还需要安装核心。
很多人估计都没有手工安装过，感觉不够友好，建议预集成可用的核心。**

1.Openclash的自动下载核心总是报错，现在是手工安装核心后才正常运行。 //如果预集成可用的核心会好很多。
  Openclash 各种类型的核心下载地址：https://github.com/vernesong/OpenClash/tree/master/core-lateset
 安装一个dev的就可以，其他等openclash正常后再手工触发更新即可。
2.AdGuardHome的核心默认也没有，也需要下载， Openclash正常后可以手工触发后自动下载。
3.这两个插件因为没有预先集成可用的核心，碰到好几个莫名奇妙的问题。

**这个有点影响对iStoreOS体验的热情啊**

**Comment by Marek778-coder** [comment]
这个核心怎么装啊，小白一个，已经折腾好几天了，一直以为是我哪里没设置好

**Comment by bluesyk** [comment]
首先内核是可以在线更新的，在openclash的总界面有按钮。
不过如果设备没有科学上网，可能无法自动更新，有的时候自动更新也会失败。

**手工安装的方式**

- **图形界面安装方式**

1.电脑科学上网
2.从[这里](https://github.com/vernesong/OpenClash/tree/master/core-lateset/dev)下载软路由硬件对应的dev内核，随便哪个版本都行。例如X86的下载https://github.com/vernesong/OpenClash/blob/master/core-lateset/dev/clash-linux-amd64.tar.gz

3.进入OpenClash，【配置文件管理】 页面，点开上传文件类型，选择dev类型，上传对应的内核文件就可以了！
（不用解压，直接上传）
![image](https://user-images.githubusercontent.com/17310897/202932784-c4dca581-ee53-4581-a0ae-349824aa799f.png)


- **命令行方式**
见内核下载章节
https://adao.me/ruanjian/216.html

**Comment by AUK9527** [comment]
openclash可以考虑加下内核，adg就算了，adg的核心很好下载。
