### ISSUE TITLE
PassWall_x86.run install failed

### ISSUE THREAD

**Issue by ghost** [AUK9527/Are-u-ok#6]
* opkg_install_cmd: Cannot install package luci-i18n-passwall-zh-cn.
 * pkg_hash_check_unresolved: cannot find dependency libev for shadowsocksr-libev-ssr-check
 * pkg_hash_check_unresolved: cannot find dependency libsodium for shadowsocksr-libev-ssr-check
 * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-check found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-check.

离线安装失败,错误码 255

**Comment by AUK9527** [comment]
> * opkg_install_cmd: Cannot install package luci-i18n-passwall-zh-cn.
> * pkg_hash_check_unresolved: cannot find dependency libev for shadowsocksr-libev-ssr-check
> * pkg_hash_check_unresolved: cannot find dependency libsodium for shadowsocksr-libev-ssr-check
> * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-check found, but incompatible with the architectures configured
> * opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-check.
> 
> 离线安装失败,错误码 255

安装新的 就成
