### ISSUE TITLE
为什么离线安装了passwall/ssr/helloworld，在已安装里都不显示？

### ISSUE THREAD

**Issue by chenxiccc** [AUK9527/Are-u-ok#7]
为什么离线安装了passwall/ssr/helloworld，在已安装里都不显示？
需要像原来的ks固件一样执行一段神秘代码才能显示吗？

**Comment by showlee** [comment]
重启，试过没有？

**Comment by vipwuping** [comment]
离线安装失败,错误码 139  我安装的是  passwall 安装不了

**Comment by AUK9527** [comment]
> 为什么离线安装了passwall/ssr/helloworld，在已安装里都不显示？ 需要像原来的ks固件一样执行一段神秘代码才能显示吗？

看是在啥固件上，如果在 openwrt 21及以上的，可能需要浏览器清除缓存 或者，在istore里 随便 装个插件，就显示了。

**Comment by wangweiweiwei** [comment]
我试了好几次， 退出重新登录就显示了

**Comment by AUK9527** [comment]
> 我试了好几次， 退出重新登录就显示了

固件luci 版本不一，浏览器缓存问题
