### ISSUE TITLE
新打包的ssrplus程序，订阅的v2ray节点全部都丢弃了。

### ISSUE THREAD

**Issue by guokai10000** [AUK9527/Are-u-ok#8]
如题，全部都丢弃了，试了试跟关键字没有关系。之前下载的版本没有问题。

**Comment by AUK9527** [comment]
> 如题，全部都丢弃了，试了试跟关键字没有关系。之前下载的版本没有问题。

可能 上游调整了luci，跟随最新的luci 编译 打包的
